export const CARD_DATA = [
    {
        id: 1,
        title: 'Task1',
        creator: 'Minh',
        status: 'New',
        discription: 'this is task 1',
    },
    {
        id: 2,
        title: 'Task2',
        creator: 'Minh',
        status: 'Done',
        discription: 'this is task 2',
    },
    {
        id: 3,
        title: 'Task3',
        creator: 'Minh',
        status: 'Done',
        discription: 'this is task 3',
    },
    {
        id: 4,
        title: 'Task4',
        creator: 'Minh',
        status: 'Doing',
        discription: 'this is task 4',
    },
    {
        id: 5,
        title: 'Task5',
        creator: 'Minh',
        status: 'New',
        discription: 'this is task 5',
    },
    {
        id: 6,
        title: 'Task6',
        creator: 'Minh',
        status: 'Doing',
        discription: 'this is task 6',
    },
    {
        id: 7,
        title: 'Task7',
        creator: 'Minh',
        status: 'New',
        discription: 'this is task 7',
    },
    {
        id: 8,
        title: 'Task8',
        creator: 'Minh',
        status: 'Done',
        discription: 'this is task 8',
    },
    {
        id: 9,
        title: 'Task9',
        creator: 'Minh',
        status: 'Doing',
        discription: 'this is task 9',
    },
    {
        id: 10,
        title: 'Task10',
        creator: 'Minh',
        status: 'New',
        discription: 'this is task 10',
    },
    {
        id: 11,
        title: 'Task11',
        creator: 'Minh',
        status: 'Doing',
        discription: 'this is task 11',
    },
    {
        id: 12,
        title: 'Task12',
        creator: 'Minh',
        status: 'New',
        discription: 'this is task 12',
    },
    {
        id: 13,
        title: 'Task13',
        creator: 'Minh',
        status: 'Doing',
        discription: 'this is task 13',
    },
    {
        id: 14,
        title: 'Task14',
        creator: 'Minh',
        status: 'Done',
        discription: 'this is task 14',
    },
    {
        id: 15,
        title: 'Task15',
        creator: 'Minh',
        status: 'Doing',
        discription: 'this is task 15',
    },
    {
        id: 16,
        title: 'Task16',
        creator: 'Minh',
        status: 'Doing',
        discription: 'this is task 16',
    },
    {
        id: 17,
        title: 'Task17',
        creator: 'Minh',
        status: 'New',
        discription: 'this is task 17',
    },
    {
        id: 18,
        title: 'Task18',
        creator: 'Minh',
        status: 'Done',
        discription: 'this is task 18',
    },
    {
        id: 19,
        title: 'Task19',
        creator: 'Minh',
        status: 'New',
        discription: 'this is task 19',
    },
    {
        id: 20,
        title: 'Task20',
        creator: 'Minh',
        status: 'Done',
        discription: 'this is task 20',
    },
]
